name:                sexpresso
version:             1.2.4.0
github:              "archambaultv/sexpresso"
license:             OtherLicense # 0BSD
author:              "Vincent Archambault-Bouffard"
maintainer:          "archambault.v@gmail.com"
copyright:           "Vincent Archambault-Bouffard"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A flexible library for parsing and printing S-expression
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/archambaultv/sexpresso#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 0.2 && < 2.2
- megaparsec >= 7.0 && < 9.7
- containers >= 0.5 && < 0.8
- bifunctors >= 5.5 && < 5.7
- recursion-schemes >= 5.1 && < 5.3

library:
  source-dirs: src

tests:
  sexpresso-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sexpresso
    - tasty >= 0.8
    - tasty-hunit >= 0.10.0.1
    - tasty-smallcheck >= 0.8
    - smallcheck >= 1.0

ghc-options:
- -Wall
